version: '3'

services:
  mumble-server:
    build:
       context: .
       dockerfile: ./Dockerfile
       args:
        - MUMBLE_SERVER=${MUMBLE_SERVER}
    container_name: ${CONTAINER_MUMBLE_WEB}
    restart: always
    ports:
      - "${port_mumble_web}:80"    
    volumes:
      - mumble-data:/mumble
      - slice:/usr/share/slice/
    environment:
      - MUMBLE_SERVER= ${MUMBLE_SERVER}    
      - VIRTUAL_HOST= ${DOMAINS}
      - LETSENCRYPT_HOST= ${DOMAINS}
      - LETSENCRYPT_EMAIL= ${LETSENCRYPT_EMAIL}

volumes:
    slice:
    mumble-data:

networks:
    default:
       external:
         name: ${NETWORK}
